//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public double Price { get; set; }
        public System.DateTime Time { get; set; }
        public string Name { get; set; }
        public double Discount_price { get; set; }
        public string İconimg { get; set; }
        public double Amount { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> subCategoryId { get; set; }
    
        public virtual SubCategory SubCategory { get; set; }
    }
}
